server:
  port: 8099

spring:
  application:
    name: spring-stt

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#google:
#  cloud:
#    speech:
#      credentials:
#        path: classpath:stt.json


app:
  stt:
    supported-formats: mp3,wav,flac,ogg,m4a
    max-duration-seconds: 600
    default-language-code: ko_KR

logging:
  level:
    root: info
    com.kjung.springsst: debug